version: "3.7"

services:

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: laravel-8.x:local
    restart: unless-stopped
    volumes:
      - ./server:/var/www/html
    depends_on:
      - db
    
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: node:local
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - ./client:/var/www/html
    depends_on:
      - server
  
  db:
    container_name: db
    image: mysql:8.3
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-database}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_USER: ${DB_USERNAME:-username}
    ports:
        - "3389:3306"

  nginx:
      container_name: nginx
      image: nginx:alpine
      restart: unless-stopped
      ports:
        - "89:80"
      volumes:
        - ./server:/var/www/html
        - ./server/docker/nginx:/etc/nginx/conf.d/