version: "3.7"

services:

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: laravel-8.x:local
    restart: unless-stopped
    volumes:
      - ./server:/var/www/html
    depends_on:
      - db
    env_file:
      - ./server/.env
    
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: node:local
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - ./client:/var/www/html
    depends_on:
      - server
  
  db:
    container_name: db
    image: mysql:8.3
    restart: unless-stopped
    environment:
      # same value of DB_DATABASE
      MYSQL_DATABASE: laravel

      # same value of DB_PASSWORD
      MYSQL_ROOT_PASSWORD: passport
      MYSQL_PASSWORD: passport

      # same value of DB_USERNAME
      MYSQL_USER: passport
    ports:
      - "3389:3306"

  nginx:
      container_name: nginx
      image: nginx:alpine
      restart: unless-stopped
      ports:
        - "89:80"
      volumes:
        - ./server:/var/www/html
        - ./server/docker/nginx:/etc/nginx/conf.d/