version: "3.7"

services:

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-8.x:latest
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
  
  db:
    container_name: db
    image: mysql:8.3
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-database}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_USER: ${DB_USERNAME:-username}
    ports:
        - "3389:3306"

  nginx:
      container_name: nginx
      image: nginx:alpine
      restart: unless-stopped
      ports:
        - "89:80"
      volumes:
        - ./:/var/www/html
        - ./docker/nginx/:/etc/nginx/conf.d/